@startuml
left to right direction

actor "Administrador" as Admin

rectangle "Sistema de Entrenamiento Cognitivo Adaptativo" {

  usecase "Configurar sistema" as CU6
  usecase "Modificar parámetros globales" as UC1

  CU6 --> UC1 
}

Admin --> CU6

@enduml