@startuml
left to right direction

actor "Usuario final" as Usuario

rectangle "Sistema de Entrenamiento Cognitivo Adaptativo" {

  usecase "Consultar progreso" as CU4
  usecase "Recuperar sesiones" as UC1
  usecase "Calcular métricas históricas" as UC2

  CU4 --> UC1 : <<include>>
  CU4 --> UC2 : <<include>>
}

Usuario --> CU4

@enduml